// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd2XJ_ag3FH7Ra1--RTcqk1zkGoLLZ0CI',
    appId: '1:914828829962:web:2f9f30b90b548b8facc6f3',
    messagingSenderId: '914828829962',
    projectId: 'imitation-game-vansh',
    authDomain: 'imitation-game-vansh.firebaseapp.com',
    storageBucket: 'imitation-game-vansh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqfDNbpt5j2TzjErNgIBfA48Oae2Eib48',
    appId: '1:914828829962:android:53b81f8f09a1f036acc6f3',
    messagingSenderId: '914828829962',
    projectId: 'imitation-game-vansh',
    storageBucket: 'imitation-game-vansh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIOiVq_Nbz5XBHV9EJXRfFmDCQD4CAnuI',
    appId: '1:914828829962:ios:d29e0bc4728c06a7acc6f3',
    messagingSenderId: '914828829962',
    projectId: 'imitation-game-vansh',
    storageBucket: 'imitation-game-vansh.firebasestorage.app',
    iosBundleId: 'com.example.ghostUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIOiVq_Nbz5XBHV9EJXRfFmDCQD4CAnuI',
    appId: '1:914828829962:ios:d29e0bc4728c06a7acc6f3',
    messagingSenderId: '914828829962',
    projectId: 'imitation-game-vansh',
    storageBucket: 'imitation-game-vansh.firebasestorage.app',
    iosBundleId: 'com.example.ghostUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd2XJ_ag3FH7Ra1--RTcqk1zkGoLLZ0CI',
    appId: '1:914828829962:web:c9d3ee3404c98945acc6f3',
    messagingSenderId: '914828829962',
    projectId: 'imitation-game-vansh',
    authDomain: 'imitation-game-vansh.firebaseapp.com',
    storageBucket: 'imitation-game-vansh.firebasestorage.app',
  );
}
